#!/usr/bin/env python3
"""Train selected MetaWorld PBRS ablations serially."""

from __future__ import annotations

import argparse
import shlex
import subprocess
import sys
from typing import Optional, Sequence

from train_metaworld_reward_serial import (
    CONDA_ENV,
    PROJECT_DIR,
    _install_signal_handlers,
    terminate_process_group,
)

# Legacy queue, retained for reference.
# ASSEMBLY_EXPERIMENTS = (
#     # ("assembly", "SHAPED_PBRS-NSTEP3-DISCOUNT0.995-", 3, 0.995, False, ()),
#     ("assembly", "SHAPED_PBRS-NSTEP1-DISCOUNT0.99-", 1, 0.99, False, ()),
#     ("assembly", "SHAPED_PBRS-NSTEP1-DISCOUNT0.995-", 1, 0.995, False, ()),
#     (
#         "assembly",
#         "SHAPED_PBRS-SCALE2-NSTEP3-DISCOUNT0.995-",
#         3,
#         0.995,
#         False,
#         (
#             "shaped_reward.sparse_scale=2",
#             "shaped_reward.pbrs_dense_scale=2",
#         ),
#     ),
#     (
#         "assembly",
#         "SHAPED_PBRS-PROGRESS_BIAS_B0.005-NSTEP3-DISCOUNT0.995-",
#         3,
#         0.995,
#         False,
#         (
#             "shaped_reward.pbrs_progress_bias_enabled=true",
#             "shaped_reward.pbrs_progress_bias_b=0.005",
#         ),
#     ),
# )
#
# OOD_FILTER_TASKS = ("disassemble", "coffee-push", "soccer-meta")
# OOD_FILTER_EXPERIMENTS = tuple(
#     (
#         task,
#         f"SHAPED_PBRS-OOD_FILTER_{'ON' if enabled else 'OFF'}-",
#         3,
#         0.995,
#         enabled,
#         (),
#     )
#     for task in OOD_FILTER_TASKS
#     for enabled in (False, True)
# )
#
# EXPERIMENTS = ASSEMBLY_EXPERIMENTS + OOD_FILTER_EXPERIMENTS

# Previous queue (disabled, retained for reference).
# The task configs below contain the checkpoint, fitted Gaussian model, and
# calibration embedding generated by run_metaworld_gaussian_pipeline.py.
# METAWORLD_GAUSSIAN_TASKS = (
#     "drawer-open",
#     "sweep-into",
#     "button-press-wall",
#     "door-lock",
#     "window-close",
#     "hammer-meta",
# )
#
# SOCCER_OOD_FILTER_ON_EXPERIMENT = (
#     "soccer-meta",
#     "SHAPED_PBRS-OOD_FILTER_ON-",
#     3,
#     0.995,
#     True,
#     (),
# )
#
# EXPERIMENTS = tuple(
#     (
#         task,
#         f"SHAPED_PBRS-NSTEP3-DISCOUNT0.995-{task.upper()}-",
#         3,
#         0.995,
#         False,
#         (),
#     )
#     for task in METAWORLD_GAUSSIAN_TASKS
# )
# EXPERIMENTS = (SOCCER_OOD_FILTER_ON_EXPERIMENT,) + EXPERIMENTS

# Active queue: only `ood_p_value_threshold` changes in the first five runs.
# All seven runs retain the tasks' default OOD-filter setting (false).
OOD_THRESHOLD_EXPERIMENTS = (
    # (
    #     "sweep-into",
    #     "SHAPED_PBRS-SWEEP_INTO-OOD_THRES_0.1-",
    #     3,
    #     0.995,
    #     False,
    #     ("shaped_reward.ood_p_value_threshold=0.1",),
    # ),
    # (
    #     "button-press-wall",
    #     "SHAPED_PBRS-BUTTON_PRESS_WALL-OOD_THRES_0.1-",
    #     3,
    #     0.995,
    #     False,
    #     ("shaped_reward.ood_p_value_threshold=0.1",),
    # ),
)

DISCOUNT_GAMMA_EXPERIMENTS = (
    (
        "button-press-wall",
        "SHAPED_PBRS-BUTTON_PRESS_WALL-DISCOUNT0.99-PBRS_GAMMA0.99-",
        3,
        0.99,
        False,
        ("shaped_reward.ood_p_value_threshold=0.1",),
    ),
    (
        "button-press-wall",
        "SHAPED_PBRS-BUTTON_PRESS_WALL-DISCOUNT0.97-PBRS_GAMMA0.97-",
        3,
        0.97,
        False,
        ("shaped_reward.ood_p_value_threshold=0.1",),
    ),
)

EXPERIMENTS = OOD_THRESHOLD_EXPERIMENTS + DISCOUNT_GAMMA_EXPERIMENTS


def build_command(
    task_config: str,
    run_name_prefix: str,
    nstep: int,
    discount: float,
    enable_ood_filter: bool,
    overrides: Sequence[str] = (),
) -> list[str]:
    command = [
        "conda",
        "run",
        "--no-capture-output",
        "-n",
        CONDA_ENV,
        "python",
        "train_mw.py",
        f"task={task_config}",
        "agent=drm_mw",
        "reward_type=sparse",
        "shaped_reward.type=pbrs",
        f"shaped_reward.enable_ood_filter={str(enable_ood_filter).lower()}",
        f"nstep={nstep}",
        "nstep_alpha=0",
        f"discount={discount}",
        "discount_alpha=0",
        "discount_beta=0",
        f"shaped_reward.pbrs_gamma={discount}",
    ]
    command.extend(overrides)
    command.append(f"wandb_run_name_prefix={run_name_prefix}")
    return command


def run_experiment(
    task_config: str,
    run_name_prefix: str,
    nstep: int,
    discount: float,
    enable_ood_filter: bool,
    overrides: Sequence[str] = (),
) -> int:
    command = build_command(
        task_config,
        run_name_prefix,
        nstep,
        discount,
        enable_ood_filter,
        overrides,
    )
    print(f"Command: {shlex.join(command)}", flush=True)
    try:
        process = subprocess.Popen(
            command,
            cwd=PROJECT_DIR,
            start_new_session=True,
        )
    except OSError as error:
        print(f"Could not start experiment: {error}", file=sys.stderr)
        return 127

    try:
        return process.wait()
    finally:
        terminate_process_group(process)


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train selected MetaWorld PBRS ablations serially."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print all commands without starting training.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    if args.dry_run:
        for experiment in EXPERIMENTS:
            print(
                shlex.join(
                    build_command(
                        *experiment,
                    )
                )
            )
        return 0

    _install_signal_handlers()

    failures = []
    for index, experiment in enumerate(EXPERIMENTS, start=1):
        task_config, _, nstep, discount, enable_ood_filter, _ = experiment
        label = (
            f"{task_config} (pbrs, nstep={nstep}, discount={discount}, "
            f"ood_filter={enable_ood_filter})"
        )
        print(f"Starting {index}/{len(EXPERIMENTS)}: {label}", flush=True)
        status = run_experiment(
            *experiment,
        )
        if status != 0:
            failures.append(f"{label} (exit={status})")
            print(f"Failed: {failures[-1]}; continuing.", file=sys.stderr)
        else:
            print(f"Finished {index}/{len(EXPERIMENTS)}: {label}", flush=True)

    if failures:
        print("Completed with failures: " + ", ".join(failures), file=sys.stderr)
        return 1
    print("All selected MetaWorld PBRS experiments finished successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
